In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('Food_Inspections_-_Map.csv')

In [3]:
df.head()

,DBA Name,AKA Name,License #,Facility Type,Risk,Address,City,State,Zip,Inspection Date,Inspection Type,Results,Violations,Latitude,Longitude,Location
0,DANY'S TACOS,DANY'S TACOS,2511723.0,Restaurant,Risk 1 (High),2857 S ST LOUIS AVE,CHICAGO,IL,60623.0,03/27/2017,License,Fail,"16. FOOD PROTECTED DURING STORAGE, PREPARATION...",41.839080,-87.712058,"(41.83908026995743, -87.71205826608029)"
1,BILLY FOOD MARKET INC,BILLY FOOD MARKET,2517614.0,NaN,Risk 3 (Low),3906 W ROOSEVELT RD,CHICAGO,IL,60624.0,03/27/2017,License,Not Ready,NaN,41.866312,-87.723032,"(41.86631164119278, -87.72303226414533)"
2,TAQUERIA HACIENDA TAPATIA,TAQUERIA HACIENDA TAPATIA,2517707.0,Restaurant,Risk 1 (High),4125 W 26TH ST,CHICAGO,IL,60623.0,03/27/2017,License Re-Inspection,Pass,2. FACILITIES TO MAINTAIN PROPER TEMPERATURE -...,41.844095,-87.728176,"(41.844095184180716, -87.7281761467924)"
3,WILD GOOSE BAR & GRILL,WILD GOOSE BAR & GRILL,12475.0,Restaurant,Risk 1 (High),4265 N LINCOLN AVE,CHICAGO,IL,60618.0,03/27/2017,Canvass,Fail,"16. FOOD PROTECTED DURING STORAGE, PREPARATION...",41.959582,-87.682398,"(41.95958202440171, -87.68239844007711)"
4,PUBLICAN TAVERN K1,PUBLICAN TAVERN K1 (T3 MAIN),34173.0,Restaurant,Risk 1 (High),11601 W TOUHY AVE,CHICAGO,IL,60666.0,03/27/2017,Canvass,Fail,18. NO EVIDENCE OF RODENT OR INSECT OUTER OPEN...,42.008536,-87.914428,"(42.008536400868735, -87.91442843927047)"

In [4]:
df.index

RangeIndex(start=0, stop=146077, step=1)

In [5]:
df.columns

Index(['DBA Name', 'AKA Name', 'License #', 'Facility Type', 'Risk', 'Address',
       'City', 'State', 'Zip', 'Inspection Date', 'Inspection Type', 'Results',
       'Violations', 'Latitude', 'Longitude', 'Location'],
      dtype='object')

In [6]:
df.shape

(146077, 16)

In [7]:
df = df.set_index('DBA Name')

In [8]:
df.head()

,AKA Name,License #,Facility Type,Risk,Address,City,State,Zip,Inspection Date,Inspection Type,Results,Violations,Latitude,Longitude,Location
DBA Name,,,,,,,,,,,,,,,
DANY'S TACOS,DANY'S TACOS,2511723.0,Restaurant,Risk 1 (High),2857 S ST LOUIS AVE,CHICAGO,IL,60623.0,03/27/2017,License,Fail,"16. FOOD PROTECTED DURING STORAGE, PREPARATION...",41.839080,-87.712058,"(41.83908026995743, -87.71205826608029)"
BILLY FOOD MARKET INC,BILLY FOOD MARKET,2517614.0,NaN,Risk 3 (Low),3906 W ROOSEVELT RD,CHICAGO,IL,60624.0,03/27/2017,License,Not Ready,NaN,41.866312,-87.723032,"(41.86631164119278, -87.72303226414533)"
TAQUERIA HACIENDA TAPATIA,TAQUERIA HACIENDA TAPATIA,2517707.0,Restaurant,Risk 1 (High),4125 W 26TH ST,CHICAGO,IL,60623.0,03/27/2017,License Re-Inspection,Pass,2. FACILITIES TO MAINTAIN PROPER TEMPERATURE -...,41.844095,-87.728176,"(41.844095184180716, -87.7281761467924)"
WILD GOOSE BAR & GRILL,WILD GOOSE BAR & GRILL,12475.0,Restaurant,Risk 1 (High),4265 N LINCOLN AVE,CHICAGO,IL,60618.0,03/27/2017,Canvass,Fail,"16. FOOD PROTECTED DURING STORAGE, PREPARATION...",41.959582,-87.682398,"(41.95958202440171, -87.68239844007711)"
PUBLICAN TAVERN K1,PUBLICAN TAVERN K1 (T3 MAIN),34173.0,Restaurant,Risk 1 (High),11601 W TOUHY AVE,CHICAGO,IL,60666.0,03/27/2017,Canvass,Fail,18. NO EVIDENCE OF RODENT OR INSECT OUTER OPEN...,42.008536,-87.914428,"(42.008536400868735, -87.91442843927047)"

In [10]:
df['Risk'].head()

DBA Name
DANY'S TACOS                 Risk 1 (High)
BILLY FOOD MARKET INC         Risk 3 (Low)
TAQUERIA HACIENDA TAPATIA    Risk 1 (High)
WILD GOOSE BAR & GRILL       Risk 1 (High)
PUBLICAN TAVERN K1           Risk 1 (High)
Name: Risk, dtype: object

In [40]:
df.Risk.head()

DBA Name
DANY'S TACOS                 Risk 1 (High)
BILLY FOOD MARKET INC         Risk 3 (Low)
TAQUERIA HACIENDA TAPATIA    Risk 1 (High)
WILD GOOSE BAR & GRILL       Risk 1 (High)
PUBLICAN TAVERN K1           Risk 1 (High)
Name: Risk, dtype: object

In [12]:
df[['Risk','Results']].head()

                                    Risk    Results
DBA Name
DANY'S TACOS               Risk 1 (High)       Fail
BILLY FOOD MARKET INC       Risk 3 (Low)  Not Ready
TAQUERIA HACIENDA TAPATIA  Risk 1 (High)       Pass
WILD GOOSE BAR & GRILL     Risk 1 (High)       Fail
PUBLICAN TAVERN K1         Risk 1 (High)       Fail

In [13]:
df[['Risk']].head()

                                    Risk
DBA Name
DANY'S TACOS               Risk 1 (High)
BILLY FOOD MARKET INC       Risk 3 (Low)
TAQUERIA HACIENDA TAPATIA  Risk 1 (High)
WILD GOOSE BAR & GRILL     Risk 1 (High)
PUBLICAN TAVERN K1         Risk 1 (High)

In [41]:
df.loc['WILD GOOSE BAR & GRILL']

,AKA Name,License #,Facility Type,Risk,Address,City,State,Zip,Inspection Date,Inspection Type,Results,Violations,Latitude,Longitude,Location
DBA Name,,,,,,,,,,,,,,,
WILD GOOSE BAR & GRILL,WILD GOOSE BAR & GRILL,12475.0,Restaurant,Risk 1 (High),4265 N LINCOLN AVE,CHICAGO,IL,60618.0,03/27/2017,Canvass,Fail,"16. FOOD PROTECTED DURING STORAGE, PREPARATION...",41.959582,-87.682398,"(41.95958202440171, -87.68239844007711)"
WILD GOOSE BAR & GRILL,WILD GOOSE BAR & GRILL,12475.0,Restaurant,Risk 1 (High),4265 N LINCOLN AVE,CHICAGO,IL,60618.0,05/23/2016,Canvass,Pass,"34. FLOORS: CONSTRUCTED PER CODE, CLEANED, GOO...",41.959582,-87.682398,"(41.95958202440171, -87.68239844007711)"
WILD GOOSE BAR & GRILL,WILD GOOSE BAR & GRILL,12475.0,Restaurant,Risk 1 (High),4265 N LINCOLN AVE,CHICAGO,IL,60618.0,10/07/2015,Canvass Re-Inspection,Pass,"16. FOOD PROTECTED DURING STORAGE, PREPARATION...",41.959582,-87.682398,"(41.95958202440171, -87.68239844007711)"
WILD GOOSE BAR & GRILL,WILD GOOSE BAR & GRILL,12475.0,Restaurant,Risk 1 (High),4265 N LINCOLN AVE,CHICAGO,IL,60618.0,09/30/2015,Canvass,Fail,29. PREVIOUS MINOR VIOLATION(S) CORRECTED 7-42...,41.959582,-87.682398,"(41.95958202440171, -87.68239844007711)"
WILD GOOSE BAR & GRILL,WILD GOOSE BAR & GRILL,12475.0,Restaurant,Risk 1 (High),4265 N LINCOLN AVE,CHICAGO,IL,60618.0,08/27/2014,Canvass,Pass,"41. PREMISES MAINTAINED FREE OF LITTER, UNNECE...",41.959582,-87.682398,"(41.95958202440171, -87.68239844007711)"
WILD GOOSE BAR & GRILL,WILD GOOSE BAR & GRILL,12475.0,Restaurant,Risk 1 (High),4265 N LINCOLN AVE,CHICAGO,IL,60618.0,08/27/2013,Canvass,Pass,"35. WALLS, CEILINGS, ATTACHED EQUIPMENT CONSTR...",41.959582,-87.682398,"(41.95958202440171, -87.68239844007711)"
WILD GOOSE BAR & GRILL,WILD GOOSE BAR & GRILL,12475.0,Restaurant,Risk 1 (High),4265 N LINCOLN AVE,CHICAGO,IL,60618.0,07/30/2012,Canvass,Pass,"30. FOOD IN ORIGINAL CONTAINER, PROPERLY LABEL...",41.959582,-87.682398,"(41.95958202440171, -87.68239844007711)"
WILD GOOSE BAR & GRILL,WILD GOOSE BAR & GRILL,12475.0,Restaurant,Risk 1 (High),4265 N LINCOLN AVE,CHICAGO,IL,60618.0,07/07/2010,Canvass,Pass,33. FOOD AND NON-FOOD CONTACT EQUIPMENT UTENSI...,41.959582,-87.682398,"(41.95958202440171, -87.68239844007711)"

In [15]:
df.loc[['WILD GOOSE BAR & GRILL','TAQUERIA HACIENDA TAPATIA'],['Risk','Results']]

                                    Risk Results
DBA Name
WILD GOOSE BAR & GRILL     Risk 1 (High)    Fail
WILD GOOSE BAR & GRILL     Risk 1 (High)    Pass
WILD GOOSE BAR & GRILL     Risk 1 (High)    Pass
WILD GOOSE BAR & GRILL     Risk 1 (High)    Fail
WILD GOOSE BAR & GRILL     Risk 1 (High)    Pass
WILD GOOSE BAR & GRILL     Risk 1 (High)    Pass
WILD GOOSE BAR & GRILL     Risk 1 (High)    Pass
WILD GOOSE BAR & GRILL     Risk 1 (High)    Pass
TAQUERIA HACIENDA TAPATIA  Risk 1 (High)    Pass
TAQUERIA HACIENDA TAPATIA  Risk 1 (High)    Fail

In [16]:
df.loc['SCRUB A DUB','Risk']

'Risk 2 (Medium)'

In [30]:
df.loc['THRESHOLD SCHOOL':'SCRUB A DUB':3]
#'Inspection Type':]

KeyError: "Cannot get left slice bound for non-unique label: 'THRESHOLD SCHOOL'"

In [42]:
df.iloc[500:510]

,AKA Name,License #,Facility Type,Risk,Address,City,State,Zip,Inspection Date,Inspection Type,Results,Violations,Latitude,Longitude,Location
DBA Name,,,,,,,,,,,,,,,
"PENINSULA CHICAGO,LLC",MAIN KITCHEN,1091966.0,Restaurant,Risk 1 (High),108 E SUPERIOR ST,CHICAGO,IL,60611.0,03/15/2017,Canvass,Fail,"16. FOOD PROTECTED DURING STORAGE, PREPARATION...",41.895840,-87.624988,"(41.89583963820686, -87.62498814131581)"
VENEZUELAN BOWL GRILL LLC,VENEZUELAN BOWL GRILL,2424110.0,Restaurant,Risk 1 (High),2436 N LINCOLN AVE,CHICAGO,IL,60614.0,03/15/2017,Canvass,Fail,"14. PREVIOUS SERIOUS VIOLATION CORRECTED, 7-42...",41.926191,-87.650017,"(41.926190902860434, -87.65001746088006)"
JULIUS MEINL,JULIUS MEINL,2141409.0,Bakery,Risk 1 (High),4115 N RAVENSWOOD AVE,CHICAGO,IL,60613.0,03/15/2017,Canvass,Pass,32. FOOD AND NON-FOOD CONTACT SURFACES PROPERL...,41.956554,-87.673709,"(41.956553643574246, -87.67370925557856)"
MEZQUITE EXPRESS # 2,MEZQUITE EXPRESS # 2,2517585.0,Restaurant,Risk 1 (High),5160 S PULASKI RD,CHICAGO,IL,60632.0,03/15/2017,License,Pass,37. TOILET ROOM DOORS SELF CLOSING: DRESSING R...,41.798750,-87.723466,"(41.79875025743268, -87.72346641018879)"
PORTILLO'S HOT DOGS,PORTILLO'S HOT DOGS,39472.0,Restaurant,Risk 1 (High),100 W ONTARIO ST,CHICAGO,IL,60654.0,03/15/2017,Complaint,Pass,38. VENTILATION: ROOMS AND EQUIPMENT VENTED AS...,41.893338,-87.631244,"(41.89333773718407, -87.63124449621304)"
SEE THRU CHINESE RESTAURANT,SEE THRU CHINESE RESTAURANT,1942299.0,Restaurant,Risk 1 (High),5609 W DIVISION ST,CHICAGO,IL,60651.0,03/15/2017,Complaint,Fail,"16. FOOD PROTECTED DURING STORAGE, PREPARATION...",41.902030,-87.766023,"(41.902029722868406, -87.76602278744853)"
DENOVA FRESH MARKET,MARTHA'S FOOD MARKET,2517805.0,Grocery Store,Risk 3 (Low),4459 W DIVERSEY AVE,CHICAGO,IL,60639.0,03/15/2017,License,Fail,18. NO EVIDENCE OF RODENT OR INSECT OUTER OPEN...,41.931521,-87.739185,"(41.93152090078495, -87.73918541762123)"
SOUTH LOOP MONTESSORI SCHOOL,SOUTH LOOP MONTESSORI SCHOOL,2517217.0,Daycare (2 - 6 Years),Risk 1 (High),47 W POLK ST,CHICAGO,IL,60605.0,03/09/2017,License,Pass,NaN,41.872167,-87.629577,"(41.87216695780119, -87.62957679729978)"
LORETTO HOSPITAL,LORETTO HOSPITAL,2204616.0,Hospital,Risk 1 (High),645 S CENTRAL AVE,CHICAGO,IL,60644.0,10/28/2016,Canvass,Pass,NaN,41.872086,-87.764430,"(41.87208576989947, -87.76443034735553)"
MONTROSE DELI & FRUIT MARKET,MONTROSE DELI & FRUIT MARKET,20886.0,Grocery Store,Risk 1 (High),5407-5411 W MONTROSE AVE,CHICAGO,IL,60641.0,03/15/2017,Complaint,Fail,3. POTENTIALLY HAZARDOUS FOOD MEETS TEMPERATUR...,41.960428,-87.762666,"(41.96042826406876, -87.7626656720388)"

In [34]:
df.iloc[[100,1000,10000],[5,3,1]]

                   City           Risk  License #
DBA Name
A-Z SALES INC.  CHICAGO  Risk 1 (High)  1490343.0
ANONG INC.      CHICAGO  Risk 1 (High)  1942424.0
ELVIA GAMA      CHICAGO  Risk 1 (High)  2423902.0

In [35]:
series = df['Risk']

In [44]:
series.head()

DBA Name
DANY'S TACOS                 Risk 1 (High)
BILLY FOOD MARKET INC         Risk 3 (Low)
TAQUERIA HACIENDA TAPATIA    Risk 1 (High)
WILD GOOSE BAR & GRILL       Risk 1 (High)
PUBLICAN TAVERN K1           Risk 1 (High)
Name: Risk, dtype: object

In [43]:
series[['ARBYS','POPEYES FAMOUS FRIED CHICKEN']].head()

DBA Name
ARBYS    Risk 1 (High)
ARBYS    Risk 1 (High)
ARBYS    Risk 1 (High)
ARBYS    Risk 1 (High)
ARBYS    Risk 1 (High)
Name: Risk, dtype: object